/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProductionsRouteImport } from './routes/productions'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as ServicesWebsiteDevelopmentRouteImport } from './routes/services.website-development'
import { Route as ServicesCustomSoftwareRouteImport } from './routes/services.custom-software'
import { Route as ServicesAutomationSystemsRouteImport } from './routes/services.automation-systems'
import { Route as ServicesAppDevelopmentRouteImport } from './routes/services.app-development'
import { Route as ServicesAiGrowthSolutionsRouteImport } from './routes/services.ai-growth-solutions'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'

const ProductionsRoute = ProductionsRouteImport.update({
  id: '/productions',
  path: '/productions',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesWebsiteDevelopmentRoute =
  ServicesWebsiteDevelopmentRouteImport.update({
    id: '/services/website-development',
    path: '/services/website-development',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesCustomSoftwareRoute = ServicesCustomSoftwareRouteImport.update({
  id: '/services/custom-software',
  path: '/services/custom-software',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesAutomationSystemsRoute =
  ServicesAutomationSystemsRouteImport.update({
    id: '/services/automation-systems',
    path: '/services/automation-systems',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesAppDevelopmentRoute = ServicesAppDevelopmentRouteImport.update({
  id: '/services/app-development',
  path: '/services/app-development',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesAiGrowthSolutionsRoute =
  ServicesAiGrowthSolutionsRouteImport.update({
    id: '/services/ai-growth-solutions',
    path: '/services/ai-growth-solutions',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/productions': typeof ProductionsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/services/ai-growth-solutions': typeof ServicesAiGrowthSolutionsRoute
  '/services/app-development': typeof ServicesAppDevelopmentRoute
  '/services/automation-systems': typeof ServicesAutomationSystemsRoute
  '/services/custom-software': typeof ServicesCustomSoftwareRoute
  '/services/website-development': typeof ServicesWebsiteDevelopmentRoute
  '/blog/': typeof BlogIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/productions': typeof ProductionsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/services/ai-growth-solutions': typeof ServicesAiGrowthSolutionsRoute
  '/services/app-development': typeof ServicesAppDevelopmentRoute
  '/services/automation-systems': typeof ServicesAutomationSystemsRoute
  '/services/custom-software': typeof ServicesCustomSoftwareRoute
  '/services/website-development': typeof ServicesWebsiteDevelopmentRoute
  '/blog': typeof BlogIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/productions': typeof ProductionsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/services/ai-growth-solutions': typeof ServicesAiGrowthSolutionsRoute
  '/services/app-development': typeof ServicesAppDevelopmentRoute
  '/services/automation-systems': typeof ServicesAutomationSystemsRoute
  '/services/custom-software': typeof ServicesCustomSoftwareRoute
  '/services/website-development': typeof ServicesWebsiteDevelopmentRoute
  '/blog/': typeof BlogIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contact'
    | '/productions'
    | '/blog/$slug'
    | '/services/ai-growth-solutions'
    | '/services/app-development'
    | '/services/automation-systems'
    | '/services/custom-software'
    | '/services/website-development'
    | '/blog/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contact'
    | '/productions'
    | '/blog/$slug'
    | '/services/ai-growth-solutions'
    | '/services/app-development'
    | '/services/automation-systems'
    | '/services/custom-software'
    | '/services/website-development'
    | '/blog'
  id:
    | '__root__'
    | '/'
    | '/contact'
    | '/productions'
    | '/blog/$slug'
    | '/services/ai-growth-solutions'
    | '/services/app-development'
    | '/services/automation-systems'
    | '/services/custom-software'
    | '/services/website-development'
    | '/blog/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactRoute: typeof ContactRoute
  ProductionsRoute: typeof ProductionsRoute
  BlogSlugRoute: typeof BlogSlugRoute
  ServicesAiGrowthSolutionsRoute: typeof ServicesAiGrowthSolutionsRoute
  ServicesAppDevelopmentRoute: typeof ServicesAppDevelopmentRoute
  ServicesAutomationSystemsRoute: typeof ServicesAutomationSystemsRoute
  ServicesCustomSoftwareRoute: typeof ServicesCustomSoftwareRoute
  ServicesWebsiteDevelopmentRoute: typeof ServicesWebsiteDevelopmentRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/productions': {
      id: '/productions'
      path: '/productions'
      fullPath: '/productions'
      preLoaderRoute: typeof ProductionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/website-development': {
      id: '/services/website-development'
      path: '/services/website-development'
      fullPath: '/services/website-development'
      preLoaderRoute: typeof ServicesWebsiteDevelopmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/custom-software': {
      id: '/services/custom-software'
      path: '/services/custom-software'
      fullPath: '/services/custom-software'
      preLoaderRoute: typeof ServicesCustomSoftwareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/automation-systems': {
      id: '/services/automation-systems'
      path: '/services/automation-systems'
      fullPath: '/services/automation-systems'
      preLoaderRoute: typeof ServicesAutomationSystemsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/app-development': {
      id: '/services/app-development'
      path: '/services/app-development'
      fullPath: '/services/app-development'
      preLoaderRoute: typeof ServicesAppDevelopmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/ai-growth-solutions': {
      id: '/services/ai-growth-solutions'
      path: '/services/ai-growth-solutions'
      fullPath: '/services/ai-growth-solutions'
      preLoaderRoute: typeof ServicesAiGrowthSolutionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactRoute: ContactRoute,
  ProductionsRoute: ProductionsRoute,
  BlogSlugRoute: BlogSlugRoute,
  ServicesAiGrowthSolutionsRoute: ServicesAiGrowthSolutionsRoute,
  ServicesAppDevelopmentRoute: ServicesAppDevelopmentRoute,
  ServicesAutomationSystemsRoute: ServicesAutomationSystemsRoute,
  ServicesCustomSoftwareRoute: ServicesCustomSoftwareRoute,
  ServicesWebsiteDevelopmentRoute: ServicesWebsiteDevelopmentRoute,
  BlogIndexRoute: BlogIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
